### ISSUE TITLE
latest commit crashes (in Anaconda 2.3)

### ISSUE THREAD

**Issue by micah541** [micah541/Ricci#17]
I'm getting the following.  I've no idea what it means

C:\Users\Micah Warren\Anaconda\Ricci\exp37\clustering\Ricci>python localricci.py
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\Micah Warren\Anaconda\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Users\Micah Warren\Anaconda\lib\threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "C:\Users\Micah Warren\Anaconda\lib\site-packages\numba\dispatcher.py", line 203, in _explain_matching_error
    raise TypeError(msg)
TypeError: No matching definition for argument type(s) array(float64, 2d, C), array(float64, 2d, C), array(float64, 2d, C)
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\Micah Warren\Anaconda\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Users\Micah Warren\Anaconda\lib\threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "C:\Users\Micah Warren\Anaconda\lib\site-packages\numba\dispatcher.py", line 203, in _explain_matching_error
    raise TypeError(msg)
TypeError: No matching definition for argument type(s) array(float64, 2d, C), array(float64, 2d, C), array(float64, 2d, C)

**Comment by micah541** [comment]
So I used Anaconda 2.5 and this did not happen.  The above happens in Anaconda 2.3.  I now have Anaconda 2.5 installed in Fenton.
